#
# This is a generated file
#
platforms:
  - &defaults
    environment:
      - GRADLE_OPTS: -Dorg.gradle.daemon=false
      - JAVA_TOOL_OPTIONS: -XX:MaxRAM=4g -XX:ParallelGCThreads=2

  - &java8
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    
  - &java11
    <<: *defaults
    docker:
      - image: circleci/openjdk:11-jdk
    

caches:
  workspace:
    - &persist-workspace
      persist_to_workspace:
        root: .
        paths: .
    - &attach-workspace
      attach_workspace:
        at: .
  test_results:
    - &store-test-results
      store_test_results:
        paths: build/test-results/
  dependencies:

    - &save-gradle-dependencies-java8
      save_cache:
        name: Saving Gradle dependencies
        key: v3-gradle-java8-{{ checksum "build.gradle.kts" }}
        paths:
          - ~/.gradle/caches/modules-2/
    - &restore-gradle-dependencies-java8
      restore_cache:
        name: Restoring Gradle dependencies
        keys:
          - v3-gradle-java8-{{ checksum "build.gradle.kts" }}
    
    - &save-gradle-dependencies-java11
      save_cache:
        name: Saving Gradle dependencies
        key: v3-gradle-java11-{{ checksum "build.gradle.kts" }}
        paths:
          - ~/.gradle/caches/modules-2/
    - &restore-gradle-dependencies-java11
      restore_cache:
        name: Restoring Gradle dependencies
        keys:
          - v3-gradle-java11-{{ checksum "build.gradle.kts" }}
    
  wrapper:

    - &save-gradle-wrapper-current
      save_cache:
        name: Saving Gradle wrapper 5.2-rc-1
        key: v2-gradle-wrapper-5.2-rc-1
        paths:
          - ~/.gradle/wrapper/dists/gradle-5.2-rc-1-bin/
          - ~/.gradle/caches/5.2-rc-1/generated-gradle-jars/
          - ~/.gradle/notifications/5.2-rc-1/
    - &restore-gradle-wrapper-current
      restore_cache:
        name: Restoring Gradle wrapper 5.2-rc-1
        keys:
          - v2-gradle-wrapper-5.2-rc-1
    
    - &save-gradle-wrapper-5-1-1
      save_cache:
        name: Saving Gradle wrapper 5.1.1
        key: v2-gradle-wrapper-5.1.1
        paths:
          - ~/.gradle/wrapper/dists/gradle-5.1.1-bin/
          - ~/.gradle/caches/5.1.1/generated-gradle-jars/
          - ~/.gradle/notifications/5.1.1/
    - &restore-gradle-wrapper-5-1-1
      restore_cache:
        name: Restoring Gradle wrapper 5.1.1
        keys:
          - v2-gradle-wrapper-5.1.1
    
    - &save-gradle-wrapper-5-0
      save_cache:
        name: Saving Gradle wrapper 5.0
        key: v2-gradle-wrapper-5.0
        paths:
          - ~/.gradle/wrapper/dists/gradle-5.0-bin/
          - ~/.gradle/caches/5.0/generated-gradle-jars/
          - ~/.gradle/notifications/5.0/
    - &restore-gradle-wrapper-5-0
      restore_cache:
        name: Restoring Gradle wrapper 5.0
        keys:
          - v2-gradle-wrapper-5.0
    
    - &save-gradle-wrapper-4-10-3
      save_cache:
        name: Saving Gradle wrapper 4.10.3
        key: v2-gradle-wrapper-4.10.3
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.10.3-bin/
          - ~/.gradle/caches/4.10.3/generated-gradle-jars/
          - ~/.gradle/notifications/4.10.3/
    - &restore-gradle-wrapper-4-10-3
      restore_cache:
        name: Restoring Gradle wrapper 4.10.3
        keys:
          - v2-gradle-wrapper-4.10.3
    
    - &save-gradle-wrapper-4-9
      save_cache:
        name: Saving Gradle wrapper 4.9
        key: v2-gradle-wrapper-4.9
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.9-bin/
          - ~/.gradle/caches/4.9/generated-gradle-jars/
          - ~/.gradle/notifications/4.9/
    - &restore-gradle-wrapper-4-9
      restore_cache:
        name: Restoring Gradle wrapper 4.9
        keys:
          - v2-gradle-wrapper-4.9
    
    - &save-gradle-wrapper-4-8-1
      save_cache:
        name: Saving Gradle wrapper 4.8.1
        key: v2-gradle-wrapper-4.8.1
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.8.1-bin/
          - ~/.gradle/caches/4.8.1/generated-gradle-jars/
          - ~/.gradle/notifications/4.8.1/
    - &restore-gradle-wrapper-4-8-1
      restore_cache:
        name: Restoring Gradle wrapper 4.8.1
        keys:
          - v2-gradle-wrapper-4.8.1
    
    - &save-gradle-wrapper-4-7
      save_cache:
        name: Saving Gradle wrapper 4.7
        key: v2-gradle-wrapper-4.7
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.7-bin/
          - ~/.gradle/caches/4.7/generated-gradle-jars/
          - ~/.gradle/notifications/4.7/
    - &restore-gradle-wrapper-4-7
      restore_cache:
        name: Restoring Gradle wrapper 4.7
        keys:
          - v2-gradle-wrapper-4.7
    
    - &save-gradle-wrapper-4-6
      save_cache:
        name: Saving Gradle wrapper 4.6
        key: v2-gradle-wrapper-4.6
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.6-bin/
          - ~/.gradle/caches/4.6/generated-gradle-jars/
          - ~/.gradle/notifications/4.6/
    - &restore-gradle-wrapper-4-6
      restore_cache:
        name: Restoring Gradle wrapper 4.6
        keys:
          - v2-gradle-wrapper-4.6
    
    - &save-gradle-wrapper-4-5-1
      save_cache:
        name: Saving Gradle wrapper 4.5.1
        key: v2-gradle-wrapper-4.5.1
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.5.1-bin/
          - ~/.gradle/caches/4.5.1/generated-gradle-jars/
          - ~/.gradle/notifications/4.5.1/
    - &restore-gradle-wrapper-4-5-1
      restore_cache:
        name: Restoring Gradle wrapper 4.5.1
        keys:
          - v2-gradle-wrapper-4.5.1
    
    - &save-gradle-wrapper-4-4-1
      save_cache:
        name: Saving Gradle wrapper 4.4.1
        key: v2-gradle-wrapper-4.4.1
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.4.1-bin/
          - ~/.gradle/caches/4.4.1/generated-gradle-jars/
          - ~/.gradle/notifications/4.4.1/
    - &restore-gradle-wrapper-4-4-1
      restore_cache:
        name: Restoring Gradle wrapper 4.4.1
        keys:
          - v2-gradle-wrapper-4.4.1
    
    - &save-gradle-wrapper-4-3-1
      save_cache:
        name: Saving Gradle wrapper 4.3.1
        key: v2-gradle-wrapper-4.3.1
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.3.1-bin/
          - ~/.gradle/caches/4.3.1/generated-gradle-jars/
          - ~/.gradle/notifications/4.3.1/
    - &restore-gradle-wrapper-4-3-1
      restore_cache:
        name: Restoring Gradle wrapper 4.3.1
        keys:
          - v2-gradle-wrapper-4.3.1
    

version: 2
jobs:
  checkout_code:
    <<: *java8
    steps:
      - checkout
      - run:
          name: Remove Git tracking files (reduces workspace size)
          command: rm -rf .git/
      - *persist-workspace

  java8:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - run:
          name: Build
          command: ./gradlew build
      - *store-test-results
      - *save-gradle-wrapper-current
      - *save-gradle-dependencies-java8
      - *persist-workspace
    
  java11:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - run:
          name: Build
          command: ./gradlew build
      - *store-test-results
      - *save-gradle-wrapper-current
      - *save-gradle-dependencies-java11
      - *persist-workspace
    
  java8_gradle51:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-5-1-1
      - run:
          name: Test against Gradle 5.1.1
          command: ./gradlew test -Ptest.gradle-version=5.1.1
      - *store-test-results
      - *save-gradle-wrapper-5-1-1
        
  java11_gradle51:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-5-1-1
      - run:
          name: Test against Gradle 5.1.1
          command: ./gradlew test -Ptest.gradle-version=5.1.1
      - *store-test-results
      - *save-gradle-wrapper-5-1-1
        
  java8_gradle50:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-5-0
      - run:
          name: Test against Gradle 5.0
          command: ./gradlew test -Ptest.gradle-version=5.0
      - *store-test-results
      - *save-gradle-wrapper-5-0
        
  java11_gradle50:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-5-0
      - run:
          name: Test against Gradle 5.0
          command: ./gradlew test -Ptest.gradle-version=5.0
      - *store-test-results
      - *save-gradle-wrapper-5-0
        
  java8_gradle410:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-10-3
      - run:
          name: Test against Gradle 4.10.3
          command: ./gradlew test -Ptest.gradle-version=4.10.3
      - *store-test-results
      - *save-gradle-wrapper-4-10-3
        
  java11_gradle410:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-10-3
      - run:
          name: Test against Gradle 4.10.3
          command: ./gradlew test -Ptest.gradle-version=4.10.3
      - *store-test-results
      - *save-gradle-wrapper-4-10-3
        
  java8_gradle49:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-9
      - run:
          name: Test against Gradle 4.9
          command: ./gradlew test -Ptest.gradle-version=4.9
      - *store-test-results
      - *save-gradle-wrapper-4-9
        
  java11_gradle49:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-9
      - run:
          name: Test against Gradle 4.9
          command: ./gradlew test -Ptest.gradle-version=4.9
      - *store-test-results
      - *save-gradle-wrapper-4-9
        
  java8_gradle48:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-8-1
      - run:
          name: Test against Gradle 4.8.1
          command: ./gradlew test -Ptest.gradle-version=4.8.1
      - *store-test-results
      - *save-gradle-wrapper-4-8-1
        
  java11_gradle48:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-8-1
      - run:
          name: Test against Gradle 4.8.1
          command: ./gradlew test -Ptest.gradle-version=4.8.1
      - *store-test-results
      - *save-gradle-wrapper-4-8-1
        
  java8_gradle47:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-7
      - run:
          name: Test against Gradle 4.7
          command: ./gradlew test -Ptest.gradle-version=4.7
      - *store-test-results
      - *save-gradle-wrapper-4-7
        
  java8_gradle46:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-6
      - run:
          name: Test against Gradle 4.6
          command: ./gradlew test -Ptest.gradle-version=4.6
      - *store-test-results
      - *save-gradle-wrapper-4-6
        
  java8_gradle45:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-5-1
      - run:
          name: Test against Gradle 4.5.1
          command: ./gradlew test -Ptest.gradle-version=4.5.1
      - *store-test-results
      - *save-gradle-wrapper-4-5-1
        
  java8_gradle44:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-4-1
      - run:
          name: Test against Gradle 4.4.1
          command: ./gradlew test -Ptest.gradle-version=4.4.1
      - *store-test-results
      - *save-gradle-wrapper-4-4-1
        
  java8_gradle43:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - *restore-gradle-wrapper-4-3-1
      - run:
          name: Test against Gradle 4.3.1
          command: ./gradlew test -Ptest.gradle-version=4.3.1
      - *store-test-results
      - *save-gradle-wrapper-4-3-1
        

workflows:
  version: 2
  tests:
    jobs:
      - checkout_code

      - java8:
          requires:
            - checkout_code
    
      - java11:
          requires:
            - java8
    
      - java8_gradle51:
          requires:
            - java8
            
        
      - java11_gradle51:
          requires:
            - java11
            - java8_gradle51
        
      - java8_gradle50:
          requires:
            - java8
            
        
      - java11_gradle50:
          requires:
            - java11
            - java8_gradle50
        
      - java8_gradle410:
          requires:
            - java8
            
        
      - java11_gradle410:
          requires:
            - java11
            - java8_gradle410
        
      - java8_gradle49:
          requires:
            - java8
            
        
      - java11_gradle49:
          requires:
            - java11
            - java8_gradle49
        
      - java8_gradle48:
          requires:
            - java8
            
        
      - java11_gradle48:
          requires:
            - java11
            - java8_gradle48
        
      - java8_gradle47:
          requires:
            - java8
            
        
      - java8_gradle46:
          requires:
            - java8
            
        
      - java8_gradle45:
          requires:
            - java8
            
        
      - java8_gradle44:
          requires:
            - java8
            
        
      - java8_gradle43:
          requires:
            - java8
            